---
title: "00_QC"
author: "Julian A Paganini"
date: "2026-02-11"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(tidyr)
library(broom)
library(dplyr)
library(readxl)
library(reshape2)
library(tidyverse)
library(viridis)
library(stringr)

```

#1. Import and wrangle Quast data
```{r}
quast_data_raw<-read.table("../results/qc/quast_report.tsv", sep="\t", header=TRUE, comment.char = "", check.names = FALSE)

quast_data_raw<-quast_data_raw[-40,]

quast_data <- quast_data_raw |>
  column_to_rownames(var = colnames(quast_data_raw)[1]) |>
  t() |>
  as.data.frame() |>
  rownames_to_column(var = "Isolate")

quast_data$`Unaligned length`<-as.numeric(quast_data$`Unaligned length`)
quast_data$`# misassemblies`<-as.numeric(quast_data$`# misassemblies`)
quast_data$`# misassembled contigs`<-as.numeric(quast_data$`# misassembled contigs`)
quast_data$`Genome fraction`<-as.numeric(quast_data$`Genome fraction`)
quast_data$`# contigs` <- as.numeric(quast_data$`# contigs`)
quast_data$`Misassembled contigs length` <- as.numeric(quast_data$`Misassembled contigs length`)
quast_data$`Total length`<-as.numeric(quast_data$`Total length`)

quast_data$`Total length`

quast_data$unaligned_contigs <- sapply(
  regmatches(
    quast_data$`# unaligned contigs`,
    gregexpr("\\d+", quast_data$`# unaligned contigs`)
  ),
  function(x) sum(as.numeric(x))
)

quast_data$misassemblies_fraction <- round(
  quast_data$`# misassembled contigs` / quast_data$`# contigs`,
  3
)

quast_data$unaligned_fraction <- round(
  quast_data$unaligned_contigs / quast_data$`# contigs`,
  3
)

write.table(quast_data, '../results/qc/FINAL_QUAST_DATA.tsv',  row.names = FALSE, sep="\t", quote = FALSE)

```

